### ISSUE TITLE
Manual update tab index workaround seems not working since version 2.7.x

### ISSUE THREAD

**Issue by nekoto-kun** [hacktons/convex_bottom_bar#134]
Hi,
I'm experiencing issue with manual workaround you give in [this reference](https://github.com/hacktons/convex_bottom_bar/blob/master/doc/issue-change-active-tab-index.md#the-raw-way), happened since I update the package from 2.6.0 to 2.7.1 recently. I've been using the suggestion successfully from the article for the past year since I don't use any controller for the bar. After the update, I'm getting exception like below and blocked my screen entirely.

```
════════ Exception caught by widgets library ═══════════════════════════════════
The following NoSuchMethodError was thrown building ConvexAppBar-[LabeledGlobalKey<ConvexAppBarState>#87f81](dirty, dependencies: [MediaQuery, _EffectiveTickerMode, Directionality], state: ConvexAppBarState#5c327(tickers: tracking 1 ticker)):
The method '/' was called on null.
Receiver: null
Tried calling: /(4)

The relevant error-causing widget was
ConvexAppBar-[LabeledGlobalKey<ConvexAppBarState>#87f81]
lib\screens\dashboard_screen.dart:350
When the exception was thrown, this was the stack
#0      Object.noSuchMethod (dart:core-patch/object_patch.dart:51:5)
#1      ConvexAppBarState.build
package:convex_bottom_bar/src/bar.dart:542
#2      StatefulElement.build
package:flutter/…/widgets/framework.dart:4744
#3      ComponentElement.performRebuild
package:flutter/…/widgets/framework.dart:4627
```
The above exception comes from below snippet.
https://github.com/hacktons/convex_bottom_bar/blob/38046c976635b2eb1e7e52bbd0f39864841fdb54/lib/src/bar.dart#L542

I've done further tracing into this file and found that ```_currentIndex``` in ```resetState()``` is set to ```null```. That results in ```convexIndex``` variable to be always ```null``` (I don't use a fixed bar)
https://github.com/hacktons/convex_bottom_bar/blob/38046c976635b2eb1e7e52bbd0f39864841fdb54/lib/src/bar.dart#L532

Below is the snippet from current version changed in 38046c976635b2eb1e7e52bbd0f39864841fdb54 commit for version 2.7.0 updated from 2.6.0.
https://github.com/hacktons/convex_bottom_bar/blob/ef34f16df6c8a8a359cd99f964c87b9affca83b4/lib/src/bar.dart#L499
If I set ```initialActiveIndex```, my bar will always selected to the specified initial index item whenever it rebuilds after coming back from other screen. I don't want that behavior so I don't set it. And if I set a controller, unfortunately I have set certain logic that needs ```currentState.animateTo(n)``` from ```AppBarKey``` defined ([as suggested from the article](https://github.com/hacktons/convex_bottom_bar/blob/master/doc/issue-change-active-tab-index.md#the-raw-way)). So I don't use a controller for that case. I don't set both ```initialActiveIndex``` and ```controller``` so logically, I will always get ```null``` based on recent package version based on that snippet. I would like to downgrade to 2.6.0 to avoid this. 

Any suggestion or fix for this? Thanks in advance.

**Comment by avenwu** [comment]
sorry about the confusion error. will double check soon

**Comment by avenwu** [comment]
@nekoto-kun Bug confirmed. Have a try on branch of `f-fix-compile-error`.

**Comment by avenwu** [comment]
@nekoto-kun 
The null exception is caused by init logic of index, I have revert some code. The latest branch of f-fix-compile-error should compile successfully. Would you switch version to help make a test if it works on your case.

**Comment by nekoto-kun** [comment]
> @nekoto-kun
> The null exception is caused by init logic of index, I have revert some code. The latest branch of f-fix-compile-error should compile successfully. Would you switch version to help make a test if it works on your case.
> 
> ```yaml
> dependency_overrides:
>   convex_bottom_bar:
>     git:
>       url: https://github.com/hacktons/convex_bottom_bar.git
>       ref: f-fix-compile-error
> ```

I've just tested using provided config and no exception found, works just fine 👍

**Comment by avenwu** [comment]
🤝 Thank you for reporting this bug.
